apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    name: memcached
spec:
  type: ClusterIP
  ports:
    - port: 11211
      targetPort: 11211
      protocol: TCP
  selector:
    name: memcached